### ISSUE TITLE
ERROR: Receving a vote from an untrusted IP

### ISSUE THREAD

**Issue by Matetv** [skypr0d/VoteTopServeur-QB#1]
[script:VoteTopServeu] ERROR: Receving a vote from an untrusted IP

**Comment by skypr0d** [comment]
I can't do anything, it's [Top Server's](https://top-serveurs.net/) code and not mine

**Comment by Matetv** [comment]
It's all ok! Just thought you had a solution for that! But thanks for the QBCore adjustment! You really saved me work!

**Comment by skypr0d** [comment]
No problem ;)
